### PR TITLE
[DEV-72384] Remove Celery task

### PR DESCRIPTION
**Pull request by dnohales**
The way the periodic task is created is no longer
supported by Celery 5, since Rover doesn't use
this feature anyway, since it doesn't use Celery
Beat, this is safe to remove.

### CODE REVIEW

**Comment by mwhansen** [comment]
It looks like we could set `STATICSITEMAPS_REFRESH_AFTER = 0` in our settings and it would disable it?

**Comment by dnohales** [comment]
The obsolete import is going to make it crash anyway.

**Comment by mwhansen** [comment]
Got it -- let's merge this into the `roverdotcom:rover` branch, and then it'll be all good!

**Comment by dnohales** [comment]
Oops!

**Comment by dnohales** [comment]
I don't have write access here.

**Comment by mwhansen** [comment]
Neither do I :-)  

@jacobdfriedmann Do you mind merging this pull request?

**Pull request merged**
